export const seedSubjects = [
  { name: 'Pharmacology', totalChapters: 12 },
  { name: 'Pathology', totalChapters: 15 },
  { name: 'Physiology', totalChapters: 10 },
  { name: 'Microbiology', totalChapters: 14 },
  { name: 'Anatomy', totalChapters: 11 },
  { name: 'Biochemistry', totalChapters: 9 },
  { name: 'Dental Materials', totalChapters: 8 },
  { name: 'Oral Pathology', totalChapters: 13 },
];

export const seedChapters = {
  'Pharmacology': [
    { name: 'General Principles', totalPages: 45 },
    { name: 'Autonomic Nervous System', totalPages: 38 },
    { name: 'Local Anesthetics', totalPages: 25 },
    { name: 'Analgesics', totalPages: 42 },
    { name: 'Antibiotics I', totalPages: 35 },
    { name: 'Antibiotics II', totalPages: 32 },
    { name: 'Antifungal & Antiviral', totalPages: 28 },
    { name: 'Cardiovascular Drugs', totalPages: 40 },
    { name: 'Respiratory Drugs', totalPages: 22 },
    { name: 'GI Drugs', totalPages: 30 },
    { name: 'Endocrine Drugs', totalPages: 36 },
    { name: 'Chemotherapy', totalPages: 33 },
  ],
  'Pathology': [
    { name: 'Cell Injury', totalPages: 40 },
    { name: 'Inflammation', totalPages: 45 },
    { name: 'Tissue Repair', totalPages: 30 },
    { name: 'Hemodynamic Disorders', totalPages: 38 },
    { name: 'Neoplasia I', totalPages: 50 },
    { name: 'Neoplasia II', totalPages: 48 },
    { name: 'Infectious Diseases', totalPages: 42 },
    { name: 'Immunology', totalPages: 55 },
    { name: 'Blood Disorders', totalPages: 35 },
    { name: 'Cardiovascular Pathology', totalPages: 40 },
    { name: 'Respiratory Pathology', totalPages: 38 },
    { name: 'GI Pathology', totalPages: 44 },
    { name: 'Renal Pathology', totalPages: 36 },
    { name: 'Endocrine Pathology', totalPages: 32 },
    { name: 'CNS Pathology', totalPages: 40 },
  ],
  'Physiology': [
    { name: 'Cell Physiology', totalPages: 35 },
    { name: 'Nerve & Muscle', totalPages: 40 },
    { name: 'Blood', totalPages: 38 },
    { name: 'Cardiovascular System', totalPages: 50 },
    { name: 'Respiratory System', totalPages: 42 },
    { name: 'Renal System', totalPages: 45 },
    { name: 'GI System', totalPages: 48 },
    { name: 'Endocrine System', totalPages: 52 },
    { name: 'Reproductive System', totalPages: 35 },
    { name: 'Nervous System', totalPages: 55 },
  ],
  'Microbiology': [
    { name: 'Introduction to Microbiology', totalPages: 25 },
    { name: 'Bacterial Structure', totalPages: 30 },
    { name: 'Bacterial Genetics', totalPages: 28 },
    { name: 'Immunology Basics', totalPages: 40 },
    { name: 'Staphylococcus & Streptococcus', totalPages: 35 },
    { name: 'Gram Positive Cocci', totalPages: 32 },
    { name: 'Gram Negative Cocci', totalPages: 28 },
    { name: 'Gram Positive Bacilli', totalPages: 30 },
    { name: 'Gram Negative Bacilli', totalPages: 38 },
    { name: 'Mycobacteria', totalPages: 35 },
    { name: 'Fungi', totalPages: 32 },
    { name: 'Viruses I', totalPages: 40 },
    { name: 'Viruses II', totalPages: 38 },
    { name: 'Parasitology', totalPages: 30 },
  ],
  'Anatomy': [
    { name: 'Head & Neck Overview', totalPages: 45 },
    { name: 'Skull', totalPages: 50 },
    { name: 'Temporomandibular Joint', totalPages: 30 },
    { name: 'Muscles of Mastication', totalPages: 28 },
    { name: 'Salivary Glands', totalPages: 32 },
    { name: 'Blood Supply of Head & Neck', totalPages: 40 },
    { name: 'Nerve Supply of Head & Neck', totalPages: 48 },
    { name: 'Oral Cavity', totalPages: 35 },
    { name: 'Teeth Morphology', totalPages: 42 },
    { name: 'Maxilla & Mandible', totalPages: 38 },
    { name: 'Lymphatics', totalPages: 30 },
  ],
  'Biochemistry': [
    { name: 'Proteins & Amino Acids', totalPages: 40 },
    { name: 'Carbohydrates', totalPages: 38 },
    { name: 'Lipids', totalPages: 35 },
    { name: 'Enzymes', totalPages: 42 },
    { name: 'Vitamins', totalPages: 30 },
    { name: 'Minerals', totalPages: 28 },
    { name: 'Nucleic Acids', totalPages: 45 },
    { name: 'Metabolism', totalPages: 50 },
    { name: 'Molecular Biology', totalPages: 40 },
  ],
  'Dental Materials': [
    { name: 'Introduction', totalPages: 25 },
    { name: 'Gypsum Products', totalPages: 30 },
    { name: 'Dental Cements', totalPages: 35 },
    { name: 'Impression Materials', totalPages: 40 },
    { name: 'Restorative Materials', totalPages: 45 },
    { name: 'Metals & Alloys', totalPages: 38 },
    { name: 'Ceramics', totalPages: 32 },
    { name: 'Polymers', totalPages: 35 },
  ],
  'Oral Pathology': [
    { name: 'Developmental Disturbances', totalPages: 40 },
    { name: 'Diseases of Teeth', totalPages: 42 },
    { name: 'Diseases of Pulp & Periapical Tissues', totalPages: 35 },
    { name: 'Periodontal Diseases', totalPages: 38 },
    { name: 'Cysts of Oral Cavity', totalPages: 45 },
    { name: 'Odontogenic Tumors', totalPages: 48 },
    { name: 'Non-Odontogenic Tumors', totalPages: 40 },
    { name: 'Salivary Gland Diseases', totalPages: 36 },
    { name: 'White Lesions', totalPages: 32 },
    { name: 'Red Lesions', totalPages: 28 },
    { name: 'Ulcerative Lesions', totalPages: 35 },
    { name: 'Vesiculobullous Lesions', totalPages: 38 },
    { name: 'Oral Manifestations of Systemic Diseases', totalPages: 42 },
  ],
};

export const motivationalQuotes = [
  "Every page you study brings you closer to your dream!",
  "Success is the sum of small efforts repeated day in and day out.",
  "You're doing amazing! Keep going!",
  "The expert in anything was once a beginner.",
  "Your hard work will pay off!",
  "Believe in yourself and all that you are.",
  "You've got this! One chapter at a time.",
  "Progress, not perfection.",
  "Your future patients are counting on you!",
  "Small steps every day lead to big results.",
  "You're stronger than you think!",
  "Knowledge is power, and you're building it every day.",
  "Don't stop when you're tired, stop when you're done!",
  "You're one day closer to becoming a dentist!",
  "Consistency is key. Keep showing up!",
];

